### ISSUE TITLE
[Bug] Crash on open - SHIELD Tablet (Android 6.0.1)

### ISSUE THREAD

**Issue by linuxct** [out386/AndroidFileHost_Browser#1]
Please, have a look. 

```--------- beginning of crash
11-24 19:06:26.174 10396 10396 E AndroidRuntime: FATAL EXCEPTION: main
11-24 19:06:26.174 10396 10396 E AndroidRuntime: Process: rom.stalker, PID: 10396
11-24 19:06:26.174 10396 10396 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-24 19:06:26.174 10396 10396 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:167)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:101)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-24 19:06:26.174 10396 10396 E AndroidRuntime:        ... 9 more
11-24 19:06:26.175   683  1208 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity```

**Comment by msfjarvis** [comment]
Hmm, I'll look into it. Thanks Sergio!

**Comment by msfjarvis** [comment]
https://jenkins.msfjarvis.me/job/afh-browser-stable/lastSuccessfulBuild/artifact/app/build/outputs/apk/afh-browser_beta_4.apk

@sergiocastell test this build and let me know if it helps with the crash

**Comment by linuxct** [comment]
@MSF-Jarvis Nop, still crashes (now in a boolean)

```--------- beginning of crash
11-24 22:52:53.054  9523  9523 E AndroidRuntime: FATAL EXCEPTION: main
11-24 22:52:53.054  9523  9523 E AndroidRuntime: Process: rom.stalker, PID: 9523
11-24 22:52:53.054  9523  9523 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnectedOrConnecting()' on a null object reference
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-24 22:52:53.054  9523  9523 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnectedOrConnecting()' on a null object reference
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:177)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:103)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-24 22:52:53.054  9523  9523 E AndroidRuntime:        ... 9 more
11-24 22:52:53.055   683  1284 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity

**Comment by msfjarvis** [comment]
it's the same crash :confused:

SIM status checks are derped :disappointed:

**Comment by linuxct** [comment]
Seems to be sth common in tablets, have a look http://stackoverflow.com/questions/31654999/boolean-android-net-networkinfo-isconnectedorconnecting-is-not-working-in-andr

**Comment by msfjarvis** [comment]
yeah I know why it's happening. I've refactored the check to be more generic and mobile network independent, test build running [here](https://jenkins.msfjarvis.me/job/afh-browser-master/10/)

**Comment by linuxct** [comment]
:disappointed: 

```--------- beginning of crash
11-24 23:21:12.101 16970 16970 E AndroidRuntime: FATAL EXCEPTION: main
11-24 23:21:12.101 16970 16970 E AndroidRuntime: Process: rom.stalker, PID: 16970
11-24 23:21:12.101 16970 16970 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-24 23:21:12.101 16970 16970 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:173)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:107)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-24 23:21:12.101 16970 16970 E AndroidRuntime:        ... 9 more
11-24 23:21:12.106   683  1498 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity


(Yes, it's the #10 execution apk, just in case...)

**Comment by msfjarvis** [comment]
![image](https://cloud.githubusercontent.com/assets/13348378/20610688/111d15e0-b2c3-11e6-811e-334643189a7a.png)

**Comment by msfjarvis** [comment]
Getting kinda rough in here :stuck_out_tongue:

**Comment by msfjarvis** [comment]
Okay I have some insight into this now. new build coming #soon

**Comment by msfjarvis** [comment]
https://jenkins.msfjarvis.me/job/afh-browser-master/11/

**Comment by linuxct** [comment]
Ayy lmao 

```--------- beginning of crash
11-24 23:55:36.361 27925 27925 E AndroidRuntime: FATAL EXCEPTION: main
11-24 23:55:36.361 27925 27925 E AndroidRuntime: Process: rom.stalker, PID: 27925
11-24 23:55:36.361 27925 27925 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-24 23:55:36.361 27925 27925 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:173)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:107)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-24 23:55:36.361 27925 27925 E AndroidRuntime:        ... 9 more
11-24 23:55:36.362   683  1284 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity

**Comment by msfjarvis** [comment]
![image](https://cloud.githubusercontent.com/assets/13348378/20610936/74364454-b2c7-11e6-8c56-906ead9fdbc3.png)

**Comment by msfjarvis** [comment]
I know what I will do now

![image](https://cloud.githubusercontent.com/assets/13348378/20610994/63eb627c-b2c8-11e6-892d-d7f610ecb103.png)

**Comment by linuxct** [comment]
Nah m8, don't worry, we'll sort it out. I'm going to fork this now.

**Comment by msfjarvis** [comment]
[the last stand](https://jenkins.msfjarvis.me/job/afh-browser-master/lastBuild/artifact/app/build/outputs/apk/afh-browser_beta_4.apk)

**Comment by linuxct** [comment]
Still failing. Ah, I want to destroy this tablet so badly

```11-26 12:14:41.342 16929 16929 E AndroidRuntime: FATAL EXCEPTION: main
11-26 12:14:41.342 16929 16929 E AndroidRuntime: Process: rom.stalker, PID: 16929
11-26 12:14:41.342 16929 16929 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 12:14:41.342 16929 16929 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:173)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:107)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-26 12:14:41.342 16929 16929 E AndroidRuntime:        ... 9 more
11-26 12:14:41.345   683  1272 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity

**Comment by linuxct** [comment]
Okay, I got an idea, there's an open source app for OTA updates handling, it's [here](https://github.com/OTAUpdateCenter/ota-updater-2.0). I remember when I used it (on my Xperia M2 tho, not sure what will happen on the tablet), it checks if the device's connected on Wifi, or on mobile data, or has no internet connection at all. Maybe it's useful.

**Comment by linuxct** [comment]
https://github.com/OTAUpdateCenter/ota-updater-2.0/blob/master/app/src/main/java/com/otaupdater/utils/Utils.java#L194

**Comment by msfjarvis** [comment]
@sergiocastell there has to be a problem.... you've got the wrong APK installed dude, I completely removed the code the stacktrace is showing. My jenkins instance wipes out the workspace before building so that's out of question too

**Comment by msfjarvis** [comment]
```java

11-26 12:14:41.342 16929 16929 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:173)

```

There's no such method anymore

**Comment by linuxct** [comment]
@MSF-Jarvis And I'm sure this is the latest version you attached from comment [263007369](https://github.com/out386/AndroidFileHost_Browser/issues/1#issuecomment-26300736)


Gave it another shot just in case, and welp... 

```11-26 13:22:55.915 10699 10699 E AndroidRuntime: FATAL EXCEPTION: main
11-26 13:22:55.915 10699 10699 E AndroidRuntime: Process: rom.stalker, PID: 10699
11-26 13:22:55.915 10699 10699 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 13:22:55.915 10699 10699 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at browser.afh.MainActivity.checkIfMobileData(MainActivity.java:173)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:107)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-26 13:22:55.915 10699 10699 E AndroidRuntime:        ... 9 more
11-26 13:22:55.916   682  1488 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity ```

**Comment by msfjarvis** [comment]
Fuck this shit it's my jenkins to blame :rage: 

https://jenkins.msfjarvis.me/job/afh-browser-master/13/

If this one doesn't work...
![photo_2016-11-26_18-04-53](https://cloud.githubusercontent.com/assets/13348378/20640401/e8b11e94-b402-11e6-8822-3be3279cdb6d.jpg)

**Comment by msfjarvis** [comment]
https://jenkins.msfjarvis.me/job/afh-browser-master/13/artifact/app/build/outputs/apk/afh-browser_beta_4.apk

**Comment by linuxct** [comment]
Now, this is something different! 

```11-26 13:41:07.723 12839 12839 D AndroidRuntime: Shutting down VM
11-26 13:41:07.772 12839 12839 E AndroidRuntime: FATAL EXCEPTION: main
11-26 13:41:07.772 12839 12839 E AndroidRuntime: Process: rom.stalker, PID: 12839
11-26 13:41:07.772 12839 12839 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{rom.stalker/browser.afh.MainActivity}: android.os.NetworkOnMainThreadException
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5460)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 13:41:07.772 12839 12839 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at java.net.InetAddress.getAllByName(InetAddress.java:215)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at browser.afh.tools.ConnectionDetector.isConnectingToInternet(ConnectionDetector.java:28)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at browser.afh.MainActivity.onCreate(MainActivity.java:102)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
11-26 13:41:07.772 12839 12839 E AndroidRuntime:        ... 9 more
11-26 13:41:07.775   682  1231 W ActivityManager:   Force finishing activity rom.stalker/browser.afh.MainActivity

**Comment by msfjarvis** [comment]
Well this one I knew would come :stuck_out_tongue_winking_eye:

**Comment by out386** [comment]
AsyncTask FTW. Sorry for not noticing, Jarv. O_O

**Comment by msfjarvis** [comment]
Nah it's my mistake, chill

**Comment by msfjarvis** [comment]
New [build](https://jenkins.msfjarvis.me/job/afh-browser-master/lastBuild/)

**Comment by linuxct** [comment]
Finally :')
Many thanks @MSF-Jarvis !!


![Screenshot_20161126-141053.png](http://i.imgur.com/YQTqIlt.png)

**Comment by msfjarvis** [comment]
Wew \*_\*
